export const REDIRECT = 'REDIRECT';
export const LOGIN_PAGE = 'LOGIN_PAGE';
export const LOGIN_PAGE_SUCCESS = 'LOGIN_PAGE_SUCCESS';
export const LOGIN_PAGE_FAILED = 'LOGIN_PAGE_FAILED';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';
export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH';
export const START_LOADING = 'START_LOADING';

