export const USER_ACTION_TYPES = {
  ADD_USER: 'ADD_USER' ,
  ADD_USER_SUCCESS: 'ADD_USER_SUCCESS' ,
  ADD_USER_FAILED: 'ADD_USER_FAILED' ,
  SELECT_USER: 'SELECT_USER',
  FETCH_USER_LIST: 'GET_LIST' ,
  FETCH_USER_LIST_SUCCESS: 'GET_LIST_SUCCESS' ,
  FETCH_USER_LIST_FAILED: 'GET_LIST_FAILED' ,
  SET_AUTHENTICATED: 'SET_AUTHENTICATED',
  GET_TOKEN: 'GET_TOKEN',
  GET_TOKEN_SUCCESS: 'GET_TOKEN_SUCCESS',
  GET_TOKEN_FAILED: 'GET_TOKEN_FAILED'
}

export const FETCH_STATUSES = {
  NOT_STARTED: 'NOT_STARTED' ,
  STARTED: 'STARTED' ,
  SUCCESS: 'SUCCESS' ,
  ERROR: 'ERROR' ,
}
